apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: linuxserver/syncthing:2.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: web
              containerPort: 8384
              protocol: TCP
            - name: sync-tcp
              containerPort: 22000
              protocol: TCP
            - name: sync-udp
              containerPort: 22000
              protocol: UDP
            - name: discovery
              containerPort: 21027
              protocol: UDP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /var/syncthing
        # - name: syncthing-configd
        #   image: ghcr.io/kastelo/syncthing-configd:latest
        #   imagePullPolicy: IfNotPresent
        #   resources:
        #     requests:
        #       cpu: 25m
        #       memory: 64Mi
        #     limits:
        #       cpu: 200m
        #       memory: 256Mi
        #   volumeMounts:
        #     - name: configd-config
        #       mountPath: /etc/syncthing-configd
        #       readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: syncthing-data
        - name: configd-config
          secret:
            secretName: syncthing-configd
