apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gw
  namespace: gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.250.0.14
  infrastructure:
    labels:
      exposure: tailnet
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.home"
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: HTTPRoute
    - name: syncthing-tcp
      protocol: TCP
      port: 22000
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: TCPRoute
