apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes

resources:
  - ns.yaml
  - pvc.yaml
  - deploy.yaml
  - svc.yaml
  - networkpolicy.yaml

secretGenerator:
  - name: hermes-env
    envs:
      - hermes.env
