apiVersion: ENC[AES256_GCM,data:m4E=,iv:URb3l/4wX9zh4wI5GsC3y1fk886l6yRxQZErV1T+NKU=,tag:/lEEz/O1z5gdS/Bi1bn6dw==,type:str]
kind: ENC[AES256_GCM,data:D1cFXON7,iv:5keXfvaETb/aAa3m1lo9ARevyq8720k1/ivKfYmqvNw=,tag:94evKvhtQBNH7ck0sfiiTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vdkVFrIOKjU=,iv:9eiX/1zVuWtZVT1wifzDp9+CmgyNrpQMhUAZy/F5LwE=,tag:YK51nP6QPlSCxtTCKzWOpg==,type:str]
    namespace: ENC[AES256_GCM,data:/6dmimIW7EszxuI=,iv:do2xx2FBCbHdXqFfhYj2+EqpCUDz7J6D6kfZ0IqeG5k=,tag:6hBcxa1PCVkbuXRjdNmxow==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:kfhIsB7JxYRwqlkWcqTD29yDSafbtTtgqXWaeLevhFGiVGvU/uLSUxHzlFFaTkvcMPTcIhJncAl1L5nbVMc4YGbIcyJqUwYxACF4CAwLaqOKH1TR6YdXViqAouoKL3fpAdBMfwxV3nwqxvf7l+zLFqPIaxWRPNBEwiV5WEY9F0E3TjPzlNq7BdBbJjL9e5kpdHbuUtlcgLM=,iv:+swHIMG1LZL+Q8BL6j+BFHIeeF+065wbAUx6bA1bXbQ=,tag:sL4CBiGVC9vxPOHULM3RZg==,type:str]
type: ENC[AES256_GCM,data:0krDpoQx,iv:T7RzCsnZyO8ndZn2Q/dyhfjtfwU4vATjOGuwjGDg9bM=,tag:FeWLtQK8E1uXEErBob8qjg==,type:str]
sops:
    age:
        - recipient: age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UkhsVTJDS29JQ3dUcFY2
            bXlwY2x3SEYwNHY0UzdiTDVxRE8rcVU0R2cwCkJNYVk5bmIrVEtGekF2dGN6U3Zv
            NktuNTRTaUU2Z0lSenE3RnVFSGFCWWMKLS0tIHV2amhXdnFueEp4WjRqYVdrbDdZ
            NjBOaklrdVE2cEdRN0pHOVAyYUpFYW8KphF9uNl5GCFNJm8oow/KC9jicKI97sco
            dPL3V6RBmHhz3q8I9O6RKEcVrPFaoCCYRjuffg050SDEPbcJ6Sl3+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1elts5hx6rdscusvp45fdu6zzf06rmccynty97t05aeegtfcgl40sq7esuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSHdyUlFrRkFMNzB3K0w5
            K09jbUpQZ1RjZktxMjhGZyt3bkM4aDNJeW00ClBkVm9ibVp2YWFwdituUkRwWm1L
            NGc3clIwd0Nnc0NaQmNwQS91ZkY4WWcKLS0tIEJWOU0rZGpINjNNcWU5S3RtSk44
            N3NxRURvSUlJQzgzd3VhRkE0S0NsVWcKzcYD0cvxju9lrR56UiIChSs+ZwwGXc2e
            mUYqBE3rh5MZr8KieLhendQWzAfaQs2X4WwtoxLsxKjPnDpFEkR6AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T18:27:44Z"
    mac: ENC[AES256_GCM,data:JcdBrqV0Go/esXIQ6i09LFSqPUy3Y+6jL64SOsy3/SP7MsR0F6emx1Bt1Te+ZIc/MQRWu5M2Bif3Aa6xE9eAGiiXEW3E9DOCeD13k86CgowUcxrTzFReR3nVW6Jzl/668yOiVogSgYWr8ohEhemSjrxmBtdLIgvy/VG7fPXpsN0=,iv:zgaglcvKRcxM8WH/ZL4ddP/vC0FZ9yJrKCDzl5Opj4Q=,tag:Oyp/KuJpykqymr+WDtAV7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
