apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - ns.yaml
  # - coredns.yaml

configMapGenerator:
  - name: values-coredns-home
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
