replicaCount: 2

serviceType: LoadBalancer

service:
  name: coredns-home
  annotations:
    lbipam.cilium.io/ips: 10.250.0.30

customLabels:
  exposure: tailnet

serviceAccount:
  create: true
rbac:
  create: true

servers:
  - zones:
      - zone: home
        use_tcp: true
    port: 1053
    servicePort: 53
    plugins:
      - name: errors
      - name: log
      - name: reload
      - name: health
        parameters: :8080
      - name: ready
        parameters: :8181
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: hosts
        configBlock: |-
          10.250.0.21 syncthing.home
          ttl 300
          fallthrough
      - name: template
        parameters: IN A home
        configBlock: |-
          match ^([a-z0-9-]+)\.home\.$
          answer "{{ .Name }} 300 IN A 10.250.0.20"
      - name: template
        parameters: IN ANY home
        configBlock: |-
          match ^([a-z0-9-]+)\.home\.$
          rcode NOERROR
