apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ns.yaml
  - local-path-provisioner.yaml

configMapGenerator:
  - name: values-local-path-provisioner
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
